server:
  port: 9022
spring:
  application:
    name: gateway
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true  #捕获404异常
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 4069MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          version: v1.0
    gateway:
      discovery:
        locator:
          enabled: true   #启用服务发现路由,使用path的时候,其实可以关闭
          lower-case-service-id: true
      routes:
        - id: acl #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://acl  #匹配后提供服务的路由地址
          predicates:
            - Path=/acl/**  #断言，路径相匹配的进行路由
        - id: edu
          uri: lb://edu
          predicates:
            - Path=/edu/**
        - id: oss
          uri: lb://oss
          predicates:
            - Path=/oss/**
        - id: vod
          uri: lb://vod
          predicates:
            - Path=/vod/**
        - id: cms
          uri: lb://cms
          predicates:
            - Path=/cms/**
        - id: msm
          uri: lb://msm
          predicates:
            - Path=/msm/**
        - id: ucenter
          uri: lb://ucenter
          predicates:
            - Path=/ucenter/**
        - id: api-ucenter
          uri: lb://ucenter
          predicates:
            - Path=/api/ucenter/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: statistics
          uri: lb://statistics
          predicates:
            - Path=/statistics/**
ribbon:
  ConnectTimeout: 1000 #连接超时时间
  ReadTimeout: 4000 #读取超时时间
  OkToRetryOnAllOperations: true #对所有操作请求进行重试
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  MaxAutoRetries: 1 #对当前实例的重试次数
logging:
  level:
    org.sang.HelloService: debug