server:
  port: 8009
spring:
  application:
    name: generator
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true  #捕获404异常
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 39.107.244.230
    port: 6379
    database: 1
    timeout: 10000
    password: 1234
    lettuce:
      pool:
        max-wait: -1ms #最大阻塞等待时间
        max-active: 20  #最大连接数
        max-idle: 10   #最大空闲连接
        min-idle: 0   #最小空闲连接
swagger:
  groupName: 分布式ID生成器接口
  backage: com.qtechweb.generator.controller