server:
  port: 8003
spring:
  application:
    name: vod
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 4069MB
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.244.230:8848
        metadata:
          version: v1.0
        group: guli
        namespace: 79e2e054-f191-4dfa-945c-ef55c6084bf1
  mvc:
    throw-exception-if-no-handler-found: true  #捕获404异常
  redis:
    host: 39.107.244.230
    port: 6379
    database: 0
    timeout: 10000
    password: 1234
    lettuce:
      pool:
        max-wait: -1ms #最大阻塞等待时间
        max-active: 20  #最大连接数
        max-idle: 10   #最大空闲连接
        min-idle: 0   #最小空闲连接
aliyun:
  vod:
    file:
      keyid: LTAI4FzqurskcBUFRiVfHKfD
      keysecret: oXj8FXiBpXPHIcbA1IO2e80Fu1EnWZ
swagger:
  groupName: Vod视频点播接口
  backage: com.qtechweb.vod.controller