server:
  port: 8002
spring:
  application:
    name: oss
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true  #捕获404异常
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.244.230:8848
        metadata:
          version: v1.0
        group: guli
        namespace: 79e2e054-f191-4dfa-945c-ef55c6084bf1
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4FzqurskcBUFRiVfHKfD
      keysecret: oXj8FXiBpXPHIcbA1IO2e80Fu1EnWZ
      bucketname: educate-guli
swagger:
  groupName: Oss对象存储接口
  backage: com.qtechweb.oss.controller